// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back.Data;

#nullable disable

namespace back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("back.Models.DB.TailingsDeposit", b =>
                {
                    b.Property<int>("DepositoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DepositoId"));

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_creacion");

                    b.Property<string>("NombreDeposito")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nombre_deposito");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Ubicacion");

                    b.HasKey("DepositoId");

                    b.ToTable("Deposito");
                });

            modelBuilder.Entity("back.Models.DB.TopographicLandmark", b =>
                {
                    b.Property<int>("HitoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HitoId"));

                    b.Property<int>("DepositoId")
                        .HasColumnType("int")
                        .HasColumnName("DepositoId");

                    b.Property<string>("NombreHito")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nombre_hito");

                    b.HasKey("HitoId");

                    b.HasIndex("DepositoId");

                    b.ToTable("Hito");
                });

            modelBuilder.Entity("back.Models.DB.TopographicMeasurements", b =>
                {
                    b.Property<int>("MedicionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MedicionId"));

                    b.Property<decimal>("AcimutAbsoluto")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("AcimutAbsoluto");

                    b.Property<decimal>("AcimutRelativo")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("AcimutRelativo");

                    b.Property<decimal>("BuzamientoAbsoluto")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("BuzamientoAbsoluto");

                    b.Property<decimal>("BuzamientoRelativo")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("BuzamientoRelativo");

                    b.Property<decimal>("Elevacion")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("Elevacion");

                    b.Property<bool>("EsBase")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("EsBase");

                    b.Property<decimal>("Este")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("Este");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("Fecha");

                    b.Property<int>("FrecuenciaMonitoreo")
                        .HasColumnType("int")
                        .HasColumnName("FrecuenciaMonitoreo");

                    b.Property<int>("HitoId")
                        .HasColumnType("int")
                        .HasColumnName("HitoId");

                    b.Property<decimal>("HorizontalAbsoluto")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("HorizontalAbsoluto");

                    b.Property<decimal>("HorizontalAcmulado")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("HorizontalAcmulado");

                    b.Property<decimal>("HorizontalRelativo")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("HorizontalRelativo");

                    b.Property<decimal>("InversaVelocidadMedia")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("InversaVelocidadMedia");

                    b.Property<decimal>("Norte")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("Norte");

                    b.Property<int>("TiempoDias")
                        .HasColumnType("int")
                        .HasColumnName("TiempoDias");

                    b.Property<decimal>("TotalAbsoluto")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("TotalAbsoluto");

                    b.Property<decimal>("TotalRelativo")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("TotalRelativo");

                    b.Property<decimal>("VelocidadMedia")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("VelocidadMedia");

                    b.Property<decimal>("VerticalAbsoluto")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("VerticalAbsoluto");

                    b.Property<decimal>("VerticalRelativo")
                        .HasColumnType("decimal(15,5)")
                        .HasColumnName("VerticalRelativo");

                    b.HasKey("MedicionId");

                    b.HasIndex("HitoId");

                    b.ToTable("Medicion");
                });

            modelBuilder.Entity("back.Models.DB.TopographicLandmark", b =>
                {
                    b.HasOne("back.Models.DB.TailingsDeposit", "Deposito")
                        .WithMany("Hitos")
                        .HasForeignKey("DepositoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposito");
                });

            modelBuilder.Entity("back.Models.DB.TopographicMeasurements", b =>
                {
                    b.HasOne("back.Models.DB.TopographicLandmark", "Hito")
                        .WithMany("Mediciones")
                        .HasForeignKey("HitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hito");
                });

            modelBuilder.Entity("back.Models.DB.TailingsDeposit", b =>
                {
                    b.Navigation("Hitos");
                });

            modelBuilder.Entity("back.Models.DB.TopographicLandmark", b =>
                {
                    b.Navigation("Mediciones");
                });
#pragma warning restore 612, 618
        }
    }
}
